excluded:
  - Carthage

opt_in_rules: # some rules are only opt-in
  - empty_count
  - anyobject_protocol
  - closure_spacing
  - implicit_return

disabled_rules:
  - weak_delegate

reporter: "xcode"
