name: Composify
on: [push]

jobs:
    build:
        name: Run Tests
        runs-on: macOS-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Setup Ruby
              uses: actions/setup-ruby@v1
              with:
                ruby-version: 2.6.6
            
            - name: Install Bundler
              run: gem install bundler:2.1.4

            - name: Cache Carthage Dependencies
              uses: actions/cache@v2
              with:
                path: Carthage
                key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
                restore-keys: ${{ runner.os }}-carthage-

            - name: Install Carthage
              run: carthage bootstrap --no-use-binaries --platform iOS --cache-builds

            - name: Install Gems
              run: bundle install

            - name: Run tests
              run: bundle exec fastlane test

