name: Composify Tests
on: [push]

jobs:
    build:
        name: Test
        runs-on: macOS-latest
        steps:
            - name: Install Carthage
              run: brew install carthage

            - name: Install Gems
              run: bundle install

            - name: Run tests
              run: bundle exec fastlane test

