# Workflow for GitHub Actions

name: CI

on:
  push:
    branches: [ integrate-github-actions ]
  pull_request:
    branches: [ master ]

jobs:
  lint-and-test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: make setup
      
      - name: Lint with SwiftLint
        run: make lint
      
      - name: Run tests
        run: bundle exec fastlane test
